package ExerciseLanguage.typesystem;

/*Generated by MPS */

import jetbrains.mps.lang.typesystem.runtime.AbstractNonTypesystemRule_Runtime;
import jetbrains.mps.lang.typesystem.runtime.NonTypesystemRule_Runtime;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.typesystem.inference.TypeCheckingContext;
import jetbrains.mps.lang.typesystem.runtime.IsApplicableStatus;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import jetbrains.mps.errors.messageTargets.MessageTarget;
import jetbrains.mps.errors.messageTargets.NodeMessageTarget;
import jetbrains.mps.errors.IErrorReporter;
import ExerciseLanguage.behavior.IEvaluatable__BehaviorDescriptor;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import org.jetbrains.mps.openapi.language.SContainmentLink;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import org.jetbrains.mps.openapi.language.SReferenceLink;
import org.jetbrains.mps.openapi.language.SProperty;
import org.jetbrains.mps.openapi.language.SConcept;

public class FunctionArgumentCheck_NonTypesystemRule extends AbstractNonTypesystemRule_Runtime implements NonTypesystemRule_Runtime {
  public FunctionArgumentCheck_NonTypesystemRule() {
  }
  public void applyRule(final SNode expression, final TypeCheckingContext typeCheckingContext, IsApplicableStatus status) {
    if (ListSequence.fromList(SLinkOperations.getChildren(expression, LINKS.arguments$myQj)).count() != ListSequence.fromList(SLinkOperations.getChildren(SLinkOperations.getTarget(expression, LINKS.function$Ocuw), LINKS.parameters$7wvy)).count()) {
      {
        final MessageTarget errorTarget = new NodeMessageTarget();
        IErrorReporter _reporter_2309309498 = typeCheckingContext.reportTypeError(expression, "wrong number of arguments, got " + ListSequence.fromList(SLinkOperations.getChildren(expression, LINKS.arguments$myQj)).count() + ", expected " + ListSequence.fromList(SLinkOperations.getChildren(SLinkOperations.getTarget(expression, LINKS.function$Ocuw), LINKS.parameters$7wvy)).count(), "r:596e03c7-07b8-4f47-94c3-e3804da5cccc(ExerciseLanguage.typesystem)", "4118362299775289668", null, errorTarget);
      }
    }

    for (int i = 0; i < ListSequence.fromList(SLinkOperations.getChildren(expression, LINKS.arguments$myQj)).count(); i++) {
      if (IEvaluatable__BehaviorDescriptor.getEvaluatedType_id1nPabnO2END.invoke(SLinkOperations.getTarget(ListSequence.fromList(SLinkOperations.getChildren(expression, LINKS.arguments$myQj)).getElement(i), LINKS.expression$aAnH)) != SPropertyOperations.getEnum(ListSequence.fromList(SLinkOperations.getChildren(SLinkOperations.getTarget(expression, LINKS.function$Ocuw), LINKS.parameters$7wvy)).getElement(i), PROPS.type$Waki)) {
        {
          final MessageTarget errorTarget = new NodeMessageTarget();
          IErrorReporter _reporter_2309309498 = typeCheckingContext.reportTypeError(ListSequence.fromList(SLinkOperations.getChildren(expression, LINKS.arguments$myQj)).getElement(i), "wrong argument #" + i + ": " + SPropertyOperations.getEnum(ListSequence.fromList(SLinkOperations.getChildren(SLinkOperations.getTarget(expression, LINKS.function$Ocuw), LINKS.parameters$7wvy)).getElement(i), PROPS.type$Waki) + "expected, got " + IEvaluatable__BehaviorDescriptor.getEvaluatedType_id1nPabnO2END.invoke(SLinkOperations.getTarget(ListSequence.fromList(SLinkOperations.getChildren(expression, LINKS.arguments$myQj)).getElement(i), LINKS.expression$aAnH)), "r:596e03c7-07b8-4f47-94c3-e3804da5cccc(ExerciseLanguage.typesystem)", "7702065012168183138", null, errorTarget);
        }
      }
    }
  }
  public SAbstractConcept getApplicableConcept() {
    return CONCEPTS.FunctionExpression$h1;
  }
  public IsApplicableStatus isApplicableAndPattern(SNode argument) {
    return new IsApplicableStatus(argument.getConcept().isSubConceptOf(getApplicableConcept()), null);
  }
  public boolean overrides() {
    return false;
  }

  private static final class LINKS {
    /*package*/ static final SContainmentLink arguments$myQj = MetaAdapterFactory.getContainmentLink(0x97a51900650f4519L, 0xa79289e9b2b161cbL, 0x304de020ebceefa4L, 0x39275cb10e731917L, "arguments");
    /*package*/ static final SReferenceLink function$Ocuw = MetaAdapterFactory.getReferenceLink(0x97a51900650f4519L, 0xa79289e9b2b161cbL, 0x304de020ebceefa4L, 0x39275cb10e71ab9cL, "function");
    /*package*/ static final SContainmentLink parameters$7wvy = MetaAdapterFactory.getContainmentLink(0x97a51900650f4519L, 0xa79289e9b2b161cbL, 0x304de020ebceefcfL, 0x665cd7dc02f6696cL, "parameters");
    /*package*/ static final SContainmentLink expression$aAnH = MetaAdapterFactory.getContainmentLink(0x97a51900650f4519L, 0xa79289e9b2b161cbL, 0x39275cb10e726720L, 0x39275cb10e726721L, "expression");
  }

  private static final class PROPS {
    /*package*/ static final SProperty type$Waki = MetaAdapterFactory.getProperty(0x97a51900650f4519L, 0xa79289e9b2b161cbL, 0x304de020ebcef043L, 0x15f528b5f406b12fL, "type");
  }

  private static final class CONCEPTS {
    /*package*/ static final SConcept FunctionExpression$h1 = MetaAdapterFactory.getConcept(0x97a51900650f4519L, 0xa79289e9b2b161cbL, 0x304de020ebceefa4L, "ExerciseLanguage.structure.FunctionExpression");
  }
}
