package ExerciseLanguage.constraints;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.base.BaseConstraintsDescriptor;
import org.jetbrains.mps.openapi.language.SConcept;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;

public class ClassRegistry_Constraints extends BaseConstraintsDescriptor {
  public ClassRegistry_Constraints() {
    super(CONCEPTS.ClassRegistry$6k);
  }

  private static final class CONCEPTS {
    /*package*/ static final SConcept ClassRegistry$6k = MetaAdapterFactory.getConcept(0x97a51900650f4519L, 0xa79289e9b2b161cbL, 0x1beda7bcefca4f4fL, "ExerciseLanguage.structure.ClassRegistry");
  }
}
