package ExerciseLanguage.constraints;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.base.BaseConstraintsDescriptor;
import org.jetbrains.mps.openapi.language.SConcept;
import org.jetbrains.mps.openapi.language.SInterfaceConcept;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;

public class IWorksheetExpression_Constraints extends BaseConstraintsDescriptor {
  public IWorksheetExpression_Constraints() {
    super(CONCEPTS.IWorksheetExpression$8J);
  }

  @Override
  public SConcept getDefaultConcreteConcept() {
    return CONCEPTS.EmptyLine$Mk;
  }

  private static final class CONCEPTS {
    /*package*/ static final SInterfaceConcept IWorksheetExpression$8J = MetaAdapterFactory.getInterfaceConcept(0x97a51900650f4519L, 0xa79289e9b2b161cbL, 0x1beda7bcefca4f54L, "ExerciseLanguage.structure.IWorksheetExpression");
    /*package*/ static final SConcept EmptyLine$Mk = MetaAdapterFactory.getConcept(0x97a51900650f4519L, 0xa79289e9b2b161cbL, 0x4c4ecad089585d2aL, "ExerciseLanguage.structure.EmptyLine");
  }
}
