package ExerciseLanguageTestLanguage.structure;

/*Generated by MPS */

import jetbrains.mps.lang.smodel.LanguageConceptIndex;
import jetbrains.mps.lang.smodel.LanguageConceptIndexBuilder;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import org.jetbrains.mps.openapi.language.SAbstractConcept;

public final class LanguageConceptSwitch {
  private final LanguageConceptIndex myIndex;
  public static final int AssertBoolean = 0;
  public static final int AssertInteger = 1;
  public static final int IAssert = 2;
  public static final int Test = 3;

  public LanguageConceptSwitch() {
    LanguageConceptIndexBuilder builder = new LanguageConceptIndexBuilder(0x18b74e1fdf5e4404L, 0x840c5428847e31a7L);
    builder.put(0x33a2ae11f0a1f024L, AssertBoolean);
    builder.put(0x33a2ae11f0a1f025L, AssertInteger);
    builder.put(0x660682a577a6bca9L, IAssert);
    builder.put(0x660682a577a6bca8L, Test);
    myIndex = builder.seal();
  }

  /*package*/ int index(SConceptId cid) {
    return myIndex.index(cid);
  }

  public int index(SAbstractConcept concept) {
    return myIndex.index(concept);
  }
}
