package ExerciseLanguage.structure;

/*Generated by MPS */

import jetbrains.mps.lang.smodel.LanguageConceptIndex;
import jetbrains.mps.lang.smodel.LanguageConceptIndexBuilder;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import org.jetbrains.mps.openapi.language.SAbstractConcept;

public final class LanguageConceptSwitch {
  private final LanguageConceptIndex myIndex;
  public static final int BooleanDeclaration = 0;
  public static final int EmptyLine = 1;
  public static final int IVariableDeclaration = 2;
  public static final int IWorksheetDeclaration = 3;
  public static final int IWorksheetExpression = 4;
  public static final int IntegerDeclaration = 5;
  public static final int VariableReference = 6;
  public static final int Worksheet = 7;
  public static final int Worksheets = 8;

  public LanguageConceptSwitch() {
    LanguageConceptIndexBuilder builder = new LanguageConceptIndexBuilder(0x97a51900650f4519L, 0xa79289e9b2b161cbL);
    builder.put(0x4c4ecad0893cc3b8L, BooleanDeclaration);
    builder.put(0x4c4ecad089585d2aL, EmptyLine);
    builder.put(0x4c4ecad0893aec5fL, IVariableDeclaration);
    builder.put(0x1beda7bcefca5f4bL, IWorksheetDeclaration);
    builder.put(0x1beda7bcefca4f54L, IWorksheetExpression);
    builder.put(0x4c4ecad0893aec64L, IntegerDeclaration);
    builder.put(0x4c4ecad0893cc3e0L, VariableReference);
    builder.put(0x1beda7bcefca4f4fL, Worksheet);
    builder.put(0x1beda7bcefca4f4eL, Worksheets);
    myIndex = builder.seal();
  }

  /*package*/ int index(SConceptId cid) {
    return myIndex.index(cid);
  }

  public int index(SAbstractConcept concept) {
    return myIndex.index(concept);
  }
}
